services:
  app:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    depends_on:
      - redis
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"